In [2]:
import numpy as np
import random

1. Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.
Expected Output:
Original List: [12.23, 13.32, 100, 36.32]
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [80]:
'''

@Author:Naveen Madev Naik
@Date: 2024-08-06
@Last Modified by: Naveen Madev Naik
@Last Modified time: 2024-08-06 
@Title :Python program to convert a list of numeric value into a one-dimensional NumPy array

'''


def list_to_numpy_array(numeric_list):
    
    """
    Description:
        function will convert list to one dimensional  numpy array

    Parameter:
        numeric_list:user input of list contains numeric value

    Return:
        None   

    """

    arr=np.array(numeric_list)
    print(f"One-dimensional numpy array: {arr}")


def main():
    try:
        no_of_item=int(input("enter the number of element value you want to add to list: "))
        print("add the numerical value: ")
        numeric_list=[]
        for item in range(no_of_item):
            numeric_list.append(float(input("add: ")))

        print(f"after converting list {numeric_list} to one-dimensional numpy array: ")
        list_to_numpy_array(numeric_list)
    
    except ValueError as e:
        print(f"Invalid input -->{e}")    

if __name__=="__main__":
    main()


Invalid input -->invalid literal for int() with base 10: 'uh'


2. Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]

In [1]:
'''

@Author:Naveen Madev Naik
@Date: 2024-08-06
@Last Modified by: Naveen Madev Naik
@Last Modified time: 2024-08-06 
@Title :Create a 3x3 matrix with values ranging from 2 to 10.

'''


def main():
    try:
        print("3X3 martix rangig from 2 to 10: ")

        matrix_list=[]
        for item in range(2,11):
            matrix_list.append(item)
        arr=np.array(matrix_list)
        arr=arr.reshape(3,3)
        print(arr)

    
    except ValueError as e:
        print(f"Invalid input -->{e}")    

if __name__=="__main__":
    main()


3X3 martix rangig from 2 to 10: 


NameError: name 'np' is not defined

3. Write a Python program to create a null vector of size 10 and update sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [82]:
'''

@Author:Naveen Madev Naik
@Date: 2024-08-06
@Last Modified by: Naveen Madev Naik
@Last Modified time: 2024-08-06 
@Title :Python program to create a null vector of size 10 and update sixth value to 11.

'''


def main():
    try:
        print("creating null vector size of 10: ")
        arr=np.zeros(10)
        print(arr)
        print("updating 6th element in array to 11: ")
        arr[6]=11
        print(arr)

    except ValueError as e:
        print(f"Invalid input -->{e}")    

if __name__=="__main__":
    main()


creating null vector size of 10: 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
updating 6th element in array to 11: 
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


4. Write a Python program to reverse an array (first element becomes last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [83]:
'''

@Author:Naveen Madev Naik
@Date: 2024-08-06
@Last Modified by: Naveen Madev Naik
@Last Modified time: 2024-08-06 
@Title :Python program to reverse an array (first element becomes last).

'''


def reverse_array(given_list):
    """
    Description:
        function will reverse given list and convert it to numpy array

    Parameter:
        given_list:user input in list

    Return:
        None

    """

    arr=np.array(given_list)
    print(arr[len(arr)-1::-1])


def main():
    try:
        no_of_element=int(input("enter number of elementy ou want to include randomly: "))
        given_list=[]
        for item in range(no_of_element):
            given_list.append(random.randint(1,100))

        print(f"After reversing given array: {given_list}: ")
        reverse_array(given_list)  


    except ValueError as e:
        print(f"Invalid input -->{e}")    

if __name__=="__main__":
    main()

Invalid input -->invalid literal for int() with base 10: 'kjhkj'


5. Write a Python program to create a 2d array with 1 on the border and 0 inside.
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 1. 1. 1. 1.]]

In [84]:
'''

@Author:Naveen Madev Naik
@Date: 2024-08-06
@Last Modified by: Naveen Madev Naik
@Last Modified time: 2024-08-06 
@Title :Python program to create a 2d array with 1 on the border and 0 inside.

'''


def main():
    try:
        matrix_row_col=int(input("enter number row column in matrix: "))

        arr=np.ones(matrix_row_col*matrix_row_col)
        arr=arr.reshape(matrix_row_col,matrix_row_col)
        print(arr)

        for row in range(1,matrix_row_col-1):
            for col in range(1,matrix_row_col-1):
                arr[row,col]=0
        print("After adding 1 on the border and 0 inside: ")        
        print(arr)

    except ValueError as e:
        print(f"Invalid input -->{e}")    

if __name__=="__main__":
    main()

Invalid input -->invalid literal for int() with base 10: ''


6. Write a Python program to add a border (filled with 0's) around an existing array.
Expected Output:
Original array:
[[ 1. 1. 1.]
[ 1. 1. 1.]
[ 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 0. 0. 0. 0. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 0. 0. 0. 0.]]

In [168]:
'''

@Author:Naveen Madev Naik
@Date: 2024-08-06
@Last Modified by: Naveen Madev Naik
@Last Modified time: 2024-08-06 
@Title : Python program to add a border (filled with 0's) around an existing array.

'''


def main():
    try:
        matrix_row_col=int(input("enter number row column in matrix: "))

        arr=np.ones(matrix_row_col*matrix_row_col)
        arr=arr.reshape(matrix_row_col,matrix_row_col)
        print(arr)
        arr = np.ones((matrix_row_col+2,matrix_row_col+2))
        print(arr)
        for row in range(0,matrix_row_col+2):
            for col in range(0,matrix_row_col+2):
                if row==0 or row==matrix_row_col-1+2 or col==0 or col==matrix_row_col-1+2:
                    arr[row,col]=0
                
   

        print("After adding 0 on the border and 1 inside: ")        
        print(arr)

    except ValueError as e:
        print(f"Invalid input -->{e}")    

if __name__=="__main__":
    main()

[[1. 1.]
 [1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
After adding 0 on the border and 1 inside: 
[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]

In [86]:
'''

@Author:Naveen Madev Naik
@Date: 2024-08-06
@Last Modified by: Naveen Madev Naik
@Last Modified time: 2024-08-06 
@Title :Python program to create a 8x8 matrix and fill it with a checkerboard pattern.

'''


def main():
    try:
        matrix_row_col=8

        arr=np.ones(matrix_row_col*matrix_row_col)
        arr=arr.reshape(matrix_row_col,matrix_row_col)

        for row in range(0,matrix_row_col):
            for col in range(0,matrix_row_col):
                if row%2==0 and col%2==0:
                    arr[row,col]=0
                elif row%2!=0 and col%2!=0:
                    arr[row,col]=0   

        print("Checkerboard Pattern: ")        
        print(arr)

    except ValueError as e:
        print(f"Invalid input -->{e}")    

if __name__=="__main__":
    main()

Checkerboard Pattern: 
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


8. Write a Python program to convert a list and tuple into arrays.
List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
[1 2 3]]

In [87]:
'''

@Author:Naveen Madev Naik
@Date: 2024-08-06
@Last Modified by: Naveen Madev Naik
@Last Modified time: 2024-08-06 
@Title :Python program to convert a list and tuple into arrays.

'''


def tuple_to_array(given_tuple):

    """
    Description:
        Function will convert tuple to array
    
    Parameter:
        given_tuple:user input of tuple

    Return:
        None
    """

    arr=np.array(given_tuple)
    print(arr)


def list_to_array(given_list):
    """
    Description:
        Function will convert list to array
    
    Parameter:
        given_tuple:user input of list

    Return:
        None
    """
    arr=np.array(given_list)
    print(arr)

    
def main():
    try:
        given_tuple=((8,4,6),(1,2,3))
        print(f"converting tuple {given_tuple} to array: ")
    
        tuple_to_array(given_tuple)

        given_list=[]
        for item in range(random.randint(4,7)):
            given_list.append(random.randint(1,10))

        print(f"converting list {given_list} to array: ") 
        list_to_array(given_list)   

    except ValueError as e:
        print(f"Invalid input -->{e}")    

if __name__=="__main__":
    main()

converting tuple ((8, 4, 6), (1, 2, 3)) to array: 
[[8 4 6]
 [1 2 3]]
converting list [5, 6, 4, 6, 5, 4] to array: 
[5 6 4 6 5 4]


9. Write a Python program to append values to the end of an array.
Expected Output:
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [88]:
'''

@Author:Naveen Madev Naik
@Date: 2024-08-06
@Last Modified by: Naveen Madev Naik
@Last Modified time: 2024-08-06 
@Title : Python program to append values to the end of an array.

'''

    
def main():
    try:
        
        arr=np.array([10,20,30])
        print("original array: ")
        print(arr)

        no_element=int(input("how many element you want to add: "))
        for item in range(no_element):
            arr=np.append(arr,int(input("add: ")))
        
        print("After append value to the end of an array: ")
        print(arr)
    except ValueError as e:
        print(f"Invalid input -->{e}")    

if __name__=="__main__":
    main()

original array: 
[10 20 30]
Invalid input -->invalid literal for int() with base 10: 'jdd'


10. Write a Python program to find the real and imaginary parts of an array of complex
numbers.
Expected Output:
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]
Real part of the array:
[ 1. 0.70710678]
Imaginary part of the array:
[ 0. 0.70710678]

In [89]:
'''

@Author:Naveen Madev Naik
@Date: 2024-08-06
@Last Modified by: Naveen Madev Naik
@Last Modified time: 2024-08-06 
@Title :Python program to find the real and imaginary parts of an array of complex numbers.

'''

    
def main():
    try:
        
        arr=np.array([ 1.0056907+0.123j, 0.70710678+0.70710678j,0.42387689+0.0087j],dtype=complex)
        print(f"Original Array: {arr}")

        real_part_arr=np.array([])
        imaginary_part_arr=np.array([])
        for index in range(len(arr)):
            real_part_arr=np.append(real_part_arr,arr[index].real)
            imaginary_part_arr=np.append(imaginary_part_arr,arr[index].imag)

        print(f"real part of an array: {real_part_arr}") 
        print(f"imaginary part of array: {imaginary_part_arr}")   
            

    except ValueError as e:
        print(f"Invalid input -->{e}")    

if __name__=="__main__":
    main()

Original Array: [1.0056907 +0.123j      0.70710678+0.70710678j 0.42387689+0.0087j    ]
real part of an array: [1.0056907  0.70710678 0.42387689]
imaginary part of array: [0.123      0.70710678 0.0087    ]


11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.
Expected Output:
Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24

In [90]:
'''

@Author:Naveen Madev Naik
@Date: 2024-08-06
@Last Modified by: Naveen Madev Naik
@Last Modified time: 2024-08-06 
@Title :Python program to find the number of elements of an array, length of one
        array element in bytes and total bytes consumed by the elements.

'''

    
def main():
    try:
        arr = np.array([1,23,4,7,8,9,10])

        num_elements = arr.size

        element_length_bytes = arr.itemsize

        total_bytes = arr.nbytes

        print(f"Number of elements in the array: {num_elements}")
        print(f"Length of one array element in bytes: {element_length_bytes}")
        print(f"Total bytes consumed by the elements: {total_bytes}")
   
            

    except ValueError as e:
        print(f"Invalid input -->{e}")    

if __name__=="__main__":
    main()

Number of elements in the array: 7
Length of one array element in bytes: 4
Total bytes consumed by the elements: 28


12. Write a Python program to find common values between two arrays.
Expected Output:
Array1: [ 0 10 20 40 60]
Array2: [10, 30, 40]
Common values between two arrays:
[10 40]

In [91]:
'''

@Author:Naveen Madev Naik
@Date: 2024-08-06
@Last Modified by: Naveen Madev Naik
@Last Modified time: 2024-08-06 
@Title :Python program to find common values between two arrays.

'''


def common_value(array1,array2):

    """
    Description:
        function will return the common element in both array inform of array

    Parameter:
        array1,array2:common element will extracted between these two array

    Return:
        None
    """
    arr=np.array([])
    for item in array2:
        if item in array1:
            arr=np.append(arr,item)
    arr=np.array(arr,dtype=int)
    print(arr)       

def main():
    try:
        array1=np.array([10,20,40,50,60])
        array2=np.array([10, 30, 40])
        print("Array1: ",array1)
        print("Array2: ",array2)

        print("common values between two arrays: ")
        common_value(array1,array2)

    except ValueError as e:
        print(f"Invalid input -->{e}")    

if __name__=="__main__":
    main()

Array1:  [10 20 40 50 60]
Array2:  [10 30 40]
common values between two arrays: 
[10 40]


13. Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2.
Expected Output:
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70, 90]
Set difference between two arrays:
[ 0 20 60 80]

In [92]:
'''

@Author:Naveen Madev Naik
@Date: 2024-08-06
@Last Modified by: Naveen Madev Naik
@Last Modified time: 2024-08-06 
@Title :Python program to find the set difference of two arrays. The set difference
        will return the sorted, unique values in array1 that are not in array2.

'''


def set_difference(array1,array2):

    """
    Description:
        function will return theset difference between two and in sorted format

    Parameter:
        array1,array2:will find set difference between this two

    Return:
        None
    """
    difference_set=set(array1)-set(array2) 
    difference_list=list(difference_set)
    difference_list.sort()
    arr=np.array(difference_list,dtype=int) 
    print(arr)    

def main():
    try:
        array1=np.array([0,10,20,40,60,80])
        array2=np.array([10, 30, 40, 50, 70, 90])
        print("Array1: ",array1)
        print("Array2: ",array2)

        print("set difference between two arrays: ")
        set_difference(array1,array2)

    except ValueError as e:
        print(f"Invalid input -->{e}")    

if __name__=="__main__":
    main()

Array1:  [ 0 10 20 40 60 80]
Array2:  [10 30 40 50 70 90]
set difference between two arrays: 
[ 0 20 60 80]


14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays.
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]

In [98]:
'''

@Author:Naveen Madev Naik
@Date: 2024-08-06
@Last Modified by: Naveen Madev Naik
@Last Modified time: 2024-08-06 
@Title :Python program to find the set exclusive-or of two arrays. Set exclusive-or
        will return the sorted, unique values that are in only one (not both) of the input arrays.

'''


def set_symetric_difference(array1,array2):

    """
    Description:
        function will return Unique values that are in only one (not both) of the input arrays

    Parameter:
        array1,array2:will find set difference between this two

    Return:
        None
    """
    union_set=set(array1)|set(array2)
    intersection_set=set(array1)&set(array2)
    difference_list=list(union_set-intersection_set)
    difference_list.sort()
    arr=np.array(difference_list,dtype=int) 
    print(arr)    

def main():
    try:
        array1=np.array([0,10,20,40,60,80])
        array2=np.array([10, 30, 40, 50, 70])
        print("Array1: ",array1)
        print("Array2: ",array2)

        print("Unique values that are in only one (not both) of the input arrays: ")
        set_symetric_difference(array1,array2)

    except ValueError as e:
        print(f"Invalid input -->{e}")    

if __name__=="__main__":
    main()

Array1:  [ 0 10 20 40 60 80]
Array2:  [10 30 40 50 70]
Unique values that are in only one (not both) of the input arrays: 
[ 0 20 30 50 60 70 80]


15. Write a Python program compare two arrays using numpy.
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]

In [118]:
'''

@Author:Naveen Madev Naik
@Date: 2024-08-06
@Last Modified by: Naveen Madev Naik
@Last Modified time: 2024-08-06 
@Title :Python program compare two arrays using numpy.

'''
   
def compare_array(array1,array2):

    """
    Descriprion:
        function will compare array in every possibility print output

    Parameter:
        array1,array2:compare this two array

    Return:
        None
    
    """

    arr=np.array(array1,dtype=bool)

    if array1.ndim == 1:
        print("\narray > array2")
        for i in range(arr.shape[0]):
            arr[i] = True if array1[i] > array2[i] else False
        print(arr)   

        print("\narray1 >= array2")
        for i in range(arr.shape[0]):
            arr[i] = True if array1[i] >= array2[i] else False
        print(arr)

        print("\narray1 < array2")
        for i in range(arr.shape[0]):
            arr[i] = True if array1[i] < array2[i] else False
        print(arr)

        print("\narray1 <= array2")
        for i in range(arr.shape[0]):
            arr[i] = True if array1[i] <= array2[i] else False
        print(arr)

    else:
        print("\narray1 > array2")
        for row in range(arr.shape[0]):
            for col in range(arr.shape[1]):
                arr[row,col]=True if array1[row,col]>array2[row,col] else False
        print(arr)   

        print("\narray1 >= array2")
        for row in range(arr.shape[0]):
            for col in range(arr.shape[1]):
                arr[row,col]=True if array1[row,col]>=array2[row,col] else False
        print(arr)

        print("\narray1 < array2")
        for row in range(arr.shape[0]):
            for col in range(arr.shape[1]):
                arr[row,col]=True if array1[row,col]<array2[row,col] else False
        print(arr)

        print("\narray1 <= array2")
        for row in range(arr.shape[0]):
            for col in range(arr.shape[1]):
                arr[row,col]=True if array1[row,col]<=array2[row,col] else False
        print(arr)       


def main():
    try:
        array1=np.array([1,0])
        array2=np.array([4,1])
        
        print("array array1: ",array1)
        print("array array2: ",array2) 

        compare_array(array1,array2)
    except ValueError as e:
        print(f"Invalid input -->{e}")    

if __name__=="__main__":
    main()

array array1:  [1 0]
array array2:  [4 1]

array > array2
[False False]

array1 >= array2
[False False]

array1 < array2
[ True  True]

array1 <= array2
[ True  True]


16. Write a Python program to create a contiguous flattened array.
Original array:
[[10 20 30]
[20 40 50]]
New flattened array:
[10 20 30 20 40 50]

In [120]:
'''

@Author:Naveen Madev Naik
@Date: 2024-08-06
@Last Modified by: Naveen Madev Naik
@Last Modified time: 2024-08-06 
@Title :Python program to create a contiguous flattened array.

'''


def main():
    try:
        arr=np.array([[10,20,40,50],[20,50,89,15]])

        print("Original Array: ",arr)
        
        flattened_array=arr.flatten()

        print("new flattened array: ")
        print(flattened_array)

    except ValueError as e:
        print(f"Invalid input -->{e}")    

if __name__=="__main__":
    main()

Original Array:  [[10 20 40 50]
 [20 50 89 15]]
new flattened array: 
[10 20 40 50 20 50 89 15]


17. Write a Python program to change the data type of an array.
Expected Output:
[[ 2 4 6]
[ 6 8 10]]
Data type of the array x is: int32
New Type: float64
[[ 2. 4. 6.]
[ 6. 8. 10.]]

In [122]:
'''

@Author:Naveen Madev Naik
@Date: 2024-08-06
@Last Modified by: Naveen Madev Naik
@Last Modified time: 2024-08-06 
@Title :Python program to change the data type of an array.

'''


def get_dtype_from_input(dtype_str):
    """
    Description:
        Convert user input string to NumPy data type.
    
    Parameter:
        dtype_str:input from user

    Return:
        string    
    """
    dtype_mapping = {
        'int32': np.int32,
        'float64': np.float64,
        'float32': np.float32,
        'int64': np.int64,
        'int16': np.int16,
        'bool': np.bool_
    }
    return dtype_mapping.get(dtype_str, None)

def main():
    try:
        arr= np.array([[2, 4, 6], [6, 8, 10]], dtype=np.int32)

        print("Original array:")
        print(arr)
        print("Data type of the array arr is:", arr.dtype)


        new_dtype_str = input("Enter the data type to convert to (e.g., 'float64', 'int32', 'bool'): ")

        new_dtype = get_dtype_from_input(new_dtype_str)

        if new_dtype is not None:
            arr_new = arr.astype(new_dtype)
            
            print("New Type:", arr_new.dtype)
            print(arr_new)
        else:
            print("Invalid data type entered. Please enter a valid NumPy data type.")
        
    except ValueError as e:
        print(f"Invalid input -->{e}")    

if __name__=="__main__":
    main()

Original array:
[[ 2  4  6]
 [ 6  8 10]]
Data type of the array arr is: int32
New Type: float32
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


18. Write a Python program to create a 3-D array with ones on a diagonal and zeros
elsewhere.
Expected Output:
[[ 1. 0. 0.]
[ 0. 1. 0.]
[ 0. 0. 1.]]

In [134]:
'''

@Author:Naveen Madev Naik
@Date: 2024-08-06
@Last Modified by: Naveen Madev Naik
@Last Modified time: 2024-08-06 
@Title :Python program to create a 3-D array with ones on a diagonal and zeros
        elsewhere.

'''


def main():
    try:
        size=int(input("enter n value for the nXnXn matrix of 3-D array: "))
        arr3d= np.zeros((size,size,size))
        print(arr3d)

        for index in range(arr3d.shape[0]):
            arr3d[index,index,index]=1

        print("after adding ones to daigonal to 3-d array: ")    
        print(arr3d)
    except ValueError as e:
        print(f"Invalid input -->{e}")    

if __name__=="__main__":
    main()

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
after adding ones to daigonal to 3-d array: 
[[[1. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 1. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 1.]]]


19. Write a Python program to create an array which looks like below array.
Expected Output:
[[ 0. 0. 0.]
[ 1. 0. 0.]
[ 1. 1. 0.]
[ 1. 1. 1.]]

In [138]:
'''

@Author:Naveen Madev Naik
@Date: 2024-08-06
@Last Modified by: Naveen Madev Naik
@Last Modified time: 2024-08-06 
@Title :Python program to create an array which looks like below array.
        Expected Output:
        [[ 0. 0. 0.]
        [ 1. 0. 0.]
        [ 1. 1. 0.]
        [ 1. 1. 1.]]

'''


def main():
    try:
        size=int(input("enter n value for the nXn matrix of 3-D array: "))
        arr2d= np.zeros((size+1,size))
        print("original array: ")
        print(arr2d)

        col_count=0
        for row in range(arr2d.shape[0]):
            for col in range(col_count):
                arr2d[row,col]=1
            col_count+=1

        print("after doing operation: ")
        print(arr2d)
            

    except ValueError as e:
        print(f"Invalid input -->{e}")    

if __name__=="__main__":
    main()

original array: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
after doing operation: 
[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


20. Write a Python program to concatenate two 2-dimensional arrays.
Expected Output:
Sample arrays: [[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]
Expected Output:
[[ 0 1 3 0 2 4]
[ 5 7 9 6 8 10]]

In [143]:
'''

@Author:Naveen Madev Naik
@Date: 2024-08-06
@Last Modified by: Naveen Madev Naik
@Last Modified time: 2024-08-06 
@Title :Python program to concatenate two 2-dimensional arrays.

'''


def main():
    try:
        array1=np.array([[1,2,3,4],[5,7,8,9]])
        array2=np.array([[2,0,6,4],[3,0,1,2]])
        print("Sample arrays: ")
        print(array1,"\n")
        print(array2)

        print("\nafter concatinating: ")
        print(np.concatenate((array1,array2),axis=1))
    
    except ValueError as e:
        print(f"Invalid input -->{e}")    

if __name__=="__main__":
    main()

Sample arrays: 
[[1 2 3 4]
 [5 7 8 9]] 

[[2 0 6 4]
 [3 0 1 2]]

after concatinating: 
[[1 2 3 4 2 0 6 4]
 [5 7 8 9 3 0 1 2]]


21. Write a Python program to make an array immutable (read-only).
Expected Output:
Test the array is read-only or not:
Try to change the value of the first element:
Traceback (most recent call last):
File "19236bd0-0bd9-11e7-a232-c706d0968eb6.py", line 6, in
x[0] = 1
ValueError: assignment destination is read-only

In [145]:
'''

@Author:Naveen Madev Naik
@Date: 2024-08-06
@Last Modified by: Naveen Madev Naik
@Last Modified time: 2024-08-06 
@Title :Python program to make an array immutable(read-only).

'''


def main():
    try:
        arr = np.array([0, 0, 0])

        arr.setflags(write=False)

        print("Test the array is read-only or not:")
        print("Array:", arr)
        print("Flags:", arr.flags)

        print("Try to change the value of the first element:")
        arr[0] = 1
    except ValueError as e:
        print("Traceback (most recent call last):")
        print("ValueError:", e)
   

if __name__=="__main__":
    main()

Test the array is read-only or not:
Array: [0 0 0]
Flags:   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

Try to change the value of the first element:
Traceback (most recent call last):
ValueError: assignment destination is read-only


22. Write a Python program to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array.
Expected Output:
Original array elements:
[[ 0 1 2 3]
[ 4 5 6 7]
[ 8 9 10 11]]
New array elements:
[[ 0 3 6 9]
[12 15 18 21]
[24 27 30 33]]

In [147]:
'''

@Author:Naveen Madev Naik
@Date: 2024-08-06
@Last Modified by: Naveen Madev Naik
@Last Modified time: 2024-08-06 
@Title :Python program to create an array of (3, 4) shape, multiply every element
        value by 3 and display the new array.

'''


def main():
    try:
        array = np.random.randint(0, 11, size=(3, 4))

        new_array = array * 3

        print("Original array:")
        print(array)
        print("New array with every element multiplied by 3:")
        print(new_array)

    except ValueError as e: 
        print(f"Invalid input -->{e}")    

if __name__=="__main__":
    main()

Original array:
[[1 3 5 0]
 [4 4 1 2]
 [4 2 3 0]]
New array with every element multiplied by 3:
[[ 3  9 15  0]
 [12 12  3  6]
 [12  6  9  0]]


23. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:
Original array elements:
[[0 1]
[2 3]
[4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]

In [149]:
'''

@Author:Naveen Madev Naik
@Date: 2024-08-06
@Last Modified by: Naveen Madev Naik
@Last Modified time: 2024-08-06 
@Title : Python program to convert a NumPy array into Python list structure.

'''


def main():
    try:
        array = np.random.randint(0, 11, size=(3, 4))

        print("Original array:")
        print(array)
        new_array_list=[]
        print("Array to list: ")
        for index in array:
            new_array_list.append(list(index))
        print(new_array_list)

    except ValueError as e: 
        print(f"Invalid input -->{e}")    

if __name__=="__main__":
    main()

Original array:
[[ 3  6  0  9]
 [ 8  3  0  5]
 [ 8  2  1 10]]
Array to list: 
[[3, 6, 0, 9], [8, 3, 0, 5], [8, 2, 1, 10]]


24. Write a Python program to convert a NumPy array with float element convert into element with 3 precisions.
Expected Output:
Original array elements:
[ 0.26153123 0.52760141 0.5718299 0.5927067 0.7831874 0.69746349
0.35399976 0.99469633 0.0694458 0.54711478]
Print array values with precision 3:
[ 0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]

In [150]:
'''

@Author:Naveen Madev Naik
@Date: 2024-08-06
@Last Modified by: Naveen Madev Naik
@Last Modified time: 2024-08-06 
@Title : Python program to convert a NumPy array with float element convert into element with 3 precisions.
'''


def main():
    try:
        array = np.array([0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874,
                  0.69746349, 0.35399976, 0.99469633, 0.0694458, 0.54711478])

        print("Original array elements:")
        print(array)

        array_rounded = np.around(array, decimals=3)
        print("Print array values with precision 3:")
        print(array_rounded)

    except ValueError as e: 
        print(f"Invalid input -->{e}")    

if __name__=="__main__":
    main()

Original array elements:
[0.26153123 0.52760141 0.5718299  0.5927067  0.7831874  0.69746349
 0.35399976 0.99469633 0.0694458  0.54711478]
Print array values with precision 3:
[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


25. Write a Python program to suppresses the use of scientific notation for small
numbers in numpy array.
Expected Output:
Original array elements:
[ 1.60000000e-10 1.60000000e+00 1.20000000e+03 2.35000000e-01]
Print array values with precision 3:
[ 0. 1.6 1200. 0.235]

In [151]:
'''

@Author:Naveen Madev Naik
@Date: 2024-08-06
@Last Modified by: Naveen Madev Naik
@Last Modified time: 2024-08-06 
@Title :Python program to suppresses the use of scientific notation for small numbers in numpy array.
'''


def main():
    try:
        array = np.array([1.6e-10, 1.6, 1200, 0.235])

        print("Original array elements:")
        print(array)

        np.set_printoptions(precision=3, suppress=True)

        print("Print array values with precision 3:")
        print(array)

    except ValueError as e: 
        print(f"Invalid input -->{e}")    

if __name__=="__main__":
    main()

Original array elements:
[1.60e-10 1.60e+00 1.20e+03 2.35e-01]
Print array values with precision 3:
[   0.       1.6   1200.       0.235]


26. Write a Python program to how to add an extra column to an numpy array.
Expected Output:
[[ 10 20 30 100]
[ 40 50 60 200]]

In [152]:
'''

@Author:Naveen Madev Naik
@Date: 2024-08-06
@Last Modified by: Naveen Madev Naik
@Last Modified time: 2024-08-06 
@Title :Python program to how to add an extra column to an numpy array.
'''


def main():
    try:
        original_array = np.array([[10, 20, 30], [40, 50, 60]])

        new_column = np.array([[100], [200]])

        result_array = np.hstack((original_array, new_column))

        print("Original array:")
        print(original_array)
        print("New array with the added column:")
        print(result_array)

    except ValueError as e: 
        print(f"Invalid input -->{e}")    

if __name__=="__main__":
    main()

Original array:
[[10 20 30]
 [40 50 60]]
New array with the added column:
[[ 10  20  30 100]
 [ 40  50  60 200]]


27. Write a Python program to remove specific elements in a numpy array.
Expected Output:
Original array:
[ 10 20 30 40 50 60 70 80 90 100]
Delete first, fourth and fifth elements:
[ 20 30 60 70 80 90 100]

In [153]:
'''

@Author:Naveen Madev Naik
@Date: 2024-08-06
@Last Modified by: Naveen Madev Naik
@Last Modified time: 2024-08-06 
@Title :Python program to remove specific elements in a numpy array.
'''

def remove_elements(arr, indices):


    """
    Description:
        Removes elements from a numpy array at specified indices.

    Parameters:
        arr (numpy.ndarray): The original array.
        indices (list or numpy.ndarray): The indices of elements to be removed.

    Returns:
    numpy.ndarray: The array with specified elements removed.

    """

    return np.delete(arr, indices)


def main():
    try:
        original_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

        indices_to_remove = [0, 3, 4]

        new_array = remove_elements(original_array, indices_to_remove)
        
        print("Original array:")
        print(original_array)
        print("Delete first, fourth and fifth elements:")
        print(new_array)

    except ValueError as e: 
        print(f"Invalid input -->{e}")    

if __name__=="__main__":
    main()

Original array:
[ 10  20  30  40  50  60  70  80  90 100]
Delete first, fourth and fifth elements:
[ 20  30  60  70  80  90 100]


28.Python program to save a NumPy array to a text file.

In [155]:
'''

@Author:Naveen Madev Naik
@Date: 2024-08-06
@Last Modified by: Naveen Madev Naik
@Last Modified time: 2024-08-06 
@Title :program to save a NumPy array to a text file.
'''


def main():
    try:
        array = np.array([[10.123, 20.456, 30.789], [40.123, 50.456, 60.789], [70.123, 80.456, 90.789]])

        filename = 'array.txt'

        np.savetxt(filename, array, fmt='%.2f', delimiter='\t')

        print(f"Array saved to {filename}")
        with open(filename, 'r') as file:
            file_content = file.read()

        print("Content of the file:")
        print(file_content)

    except ValueError as e: 
        print(f"Invalid input -->{e}")    

if __name__=="__main__":
    main()

Array saved to array.txt
Content of the file:
10.12	20.46	30.79
40.12	50.46	60.79
70.12	80.46	90.79

